name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_icolors:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'colorsapisaran' }}
 