name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_icolors:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'colorsapisaran' }}
      run: |
        docker login -username=saravanakumar491993@gmail.com -password=41daef79-26b4-42dd-b69a-767787b600c2 registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
 