name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_icolors:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'colorsapisaran' }}
      run: |
        docker login registry.heroku.com --username=$HEROKU_USER_NAME --password=$HEROKU_API_KEY 
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
 